export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Matematik", "Geometri"],
    classes: ["1B", "2A", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Fizik", "Kimya"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biyoloji"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Tarih"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Müzik", "Tarih"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Fizik"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["İngilizce", "İspanyolca"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Matematik", "Geometri"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Edebiyat", "İngilizce"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 11,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biyoloji"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 12,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biyoloji"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 13,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biyoloji"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 14,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biyoloji"],
    classes: ["5A", "4B", "3C"],
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Atatürk Caddesi No: 123, Beşiktaş, İstanbul, Türkiye",
  },
];

export const subjectsData = [
  {
    id: 1,
    lessonName: "Matematik",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    lessonName: "İngilizce",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    lessonName: "Fizik",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    lessonName: "Kimya",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    lessonName: "Biyoloji",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    lessonName: "Tarih",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    lessonName: "Geometri",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    lessonName: "Resim",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    lessonName: "Müzik",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    lessonName: "Edebiyat",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    classname: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    classname: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    classname: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    classname: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    classname: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    classname: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    classname: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    classname: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    classname: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    classname: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Matematik",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "İngilizce",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Fen Bilimleri",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Hayat Bilgisi",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Resim",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Müzik",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "Tarih",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geometri",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Fizik",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Kimya",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Matematik",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "İngilizce",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Fen Bilimleri",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Hayat Bilgisi",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Resim",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Müzik",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "Tarih",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geometri",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Fizik",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Kimya",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Matematik",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "İngilizce",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Fen Bilimleri",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Hayat Bilgisi",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Resim",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Müzik",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "Tarih",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geometri",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Fizik",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Kimya",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Matematik",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "İngilizce",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Fen Bilimleri",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Hayat Bilgisi",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Resim",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Müzik",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "Tarih",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geometri",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Fizik",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Kimya",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Göl Gezisi",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Piknik",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Plaj Gezisi",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Müze Gezisi",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Konser",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Sihirbaz Gösterisi",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Göl Gezisi",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Bisiklet Yarışı",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Sanat Sergisi Gezisi",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Futbol Turnuvası",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "4A Matematik Testi Hakkında",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "3A Fen Bilimleri Testi Hakkında",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "3B Hayat Bilgisi Testi Hakkında",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "6A İngilizce Testi Hakkında",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "8C Geometri Testi Hakkında",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "2A Matematik Testi Hakkında",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "4C Hayat Bilgisi Testi Hakkında",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "4B Matematik Testi Hakkında",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "3C İngilizce Testi Hakkında",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "1C Matematik Testi Hakkında",
    class: "1C",
    date: "2025-01-01",
  },
];

export const calendarEvents = [
  {
    title: "Matematik",
    allDay: false,
    start: new Date(2024, 9, 12, 11, 0),
    end: new Date(2024, 9, 12, 12, 0),
  },
  {
    title: "İngilizce",
    allDay: false,
    start: new Date(2024, 9, 12, 9, 0),
    end: new Date(2024, 9, 12, 10, 0),
  },
  {
    title: "Biyoloji",
    allDay: false,
    start: new Date(2024, 9, 12, 13, 0),
    end: new Date(2024, 9, 12, 14, 0),
  },
  {
    title: "Fizik",
    allDay: false,
    start: new Date(2024, 9, 12, 15, 0),
    end: new Date(2024, 9, 12, 16, 0),
  },
  {
    title: "Kimya",
    allDay: false,
    start: new Date(2024, 9, 8, 13, 0),
    end: new Date(2024, 9, 8, 13, 45),
  },
  {
    title: "Tarih",
    allDay: false,
    start: new Date(2024, 9, 8, 11, 0),
    end: new Date(2024, 9, 8, 11, 45),
  },
  {
    title: "İngilizce",
    allDay: false,
    start: new Date(2024, 9, 11, 13, 0),
    end: new Date(2024, 9, 11, 13, 45),
  },
  {
    title: "Biyoloji",
    allDay: false,
    start: new Date(2024, 9, 7, 8, 0),
    end: new Date(2024, 9, 7, 8, 45),
  },
  {
    title: "Fizik",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "Tarih",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Matematik",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biyoloji",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Kimya",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "Tarih",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "İngilizce",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biyoloji",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Fizik",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "Tarih",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Matematik",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "İngilizce",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Fizik",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Kimya",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "Tarih",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];
